#pragma once

// From glfw3.h keycodes
#define SIDEA_MOUSE_BUTTON_1         0
#define SIDEA_MOUSE_BUTTON_2         1
#define SIDEA_MOUSE_BUTTON_3         2
#define SIDEA_MOUSE_BUTTON_4         3
#define SIDEA_MOUSE_BUTTON_5         4
#define SIDEA_MOUSE_BUTTON_6         5
#define SIDEA_MOUSE_BUTTON_7         6
#define SIDEA_MOUSE_BUTTON_8         7
#define SIDEA_MOUSE_BUTTON_LAST      SIDEA_MOUSE_BUTTON_8
#define SIDEA_MOUSE_BUTTON_LEFT      SIDEA_MOUSE_BUTTON_1
#define SIDEA_MOUSE_BUTTON_RIGHT     SIDEA_MOUSE_BUTTON_2
#define SIDEA_MOUSE_BUTTON_MIDDLE    SIDEA_MOUSE_BUTTON_3